const fs = require('fs');
const path = require('path');
const cheerio = require('cheerio');

const projectRoot = path.resolve(__dirname, '..');
const parentRoot = path.resolve(projectRoot, '..');
const manifestPath = path.join(parentRoot, 'content-manifest.json');
const outputPath = path.join(projectRoot, 'src', 'constants', 'nexoHtmlData.js');

const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));

function extractAndWrap(html, isBook) {
  const $ = cheerio.load(html);

  $('script[src]').remove();
  $('.theme-toggle, .back-link').remove();

  if (isBook) {
    $('header.hero, section.hero, .hero').remove();
    $('nav, footer').remove();
  }

  const contentHtml = $('body').html() || '';
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
<style>
*{margin:0;padding:0;box-sizing:border-box}
body{background:#080c08;color:#e0e0e0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',system-ui,sans-serif;font-size:16px;line-height:1.7;-webkit-font-smoothing:antialiased}
</style>
</head>
<body>
${contentHtml}
</body>
</html>`;
}

const lessonHtml = {};
for (const [subject, lessons] of Object.entries(manifest.studyNotes)) {
  lessonHtml[subject] = {};
  for (const lesson of lessons) {
    const lessonDir = path.join(parentRoot, subject, 'lessons', String(lesson.lesson));

    let htmlPath = null;
    for (const f of lesson.files) {
      if (f.endsWith('.html')) {
        const candidate = path.join(lessonDir, f);
        if (fs.existsSync(candidate)) {
          htmlPath = candidate;
          break;
        }
      }
    }
    if (!htmlPath) {
      htmlPath = path.join(lessonDir, 'index.html');
    }

    if (fs.existsSync(htmlPath)) {
      const html = fs.readFileSync(htmlPath, 'utf8');
      lessonHtml[subject][String(lesson.lesson)] = extractAndWrap(html, false);
      console.log(`  ✓ ${subject} lesson ${lesson.lesson} (${lesson.title})`);
    } else {
      console.log(`  ✗ ${subject} lesson ${lesson.lesson} — not found at ${htmlPath}`);
    }
  }
}

const booksDir = path.join(parentRoot, 'books');
const bookDirs = fs.readdirSync(booksDir).filter(d => {
  return fs.statSync(path.join(booksDir, d)).isDirectory();
});

const bookHtml = {};
for (const dir of bookDirs) {
  const htmlPath = path.join(booksDir, dir, 'index.html');
  if (fs.existsSync(htmlPath)) {
    const html = fs.readFileSync(htmlPath, 'utf8');
    bookHtml[dir] = extractAndWrap(html, true);
    console.log(`  ✓ book ${dir}`);
  } else {
    console.log(`  ✗ book ${dir} — no index.html`);
  }
}

const content = `// Generated by scripts/generateHtmlData.js — do not edit directly
// Contains sanitized HTML content for WebView rendering.

export const LESSON_HTML = ${JSON.stringify(lessonHtml, null, 2)};

export const BOOK_HTML = ${JSON.stringify(bookHtml, null, 2)};
`;

fs.writeFileSync(outputPath, content, 'utf8');
console.log(`\nDone → ${outputPath}`);
